optimizer_args:
  optimizer_class_args:
    - params: model.prompt1.parameters()
      lr: 3.e-3
    - params: model.prompt2.parameters()
      lr: 3.e-3
    - params: model.get_mask.parameters()
      lr: ${training_args.learning_rate} * 10 
    - params: model.bert.parameters()
      lr: "${training_args.learning_rate}"
batcher_function: prompt